/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author emman
 */
public class CadastroView extends javax.swing.JFrame {

    /** Creates new form CadastroView */
    public CadastroView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUser2 = new javax.swing.JLabel();
        tfieldUser2 = new javax.swing.JTextField();
        labelSenha2 = new javax.swing.JLabel();
        tfieldSenha1 = new javax.swing.JTextField();
        labelServidor2 = new javax.swing.JLabel();
        tfieldUser3 = new javax.swing.JTextField();
        labelUser3 = new javax.swing.JLabel();
        tfieldServer3 = new javax.swing.JTextField();

        labelUser2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelUser2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUser2.setText("Nome:");
        labelUser2.setToolTipText("");

        labelSenha2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSenha2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSenha2.setText("E-mail:");

        labelServidor2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelServidor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelServidor2.setText("Password:");

        labelUser3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelUser3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUser3.setText("CEP:");
        labelUser3.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(304, 348));
        setMinimumSize(new java.awt.Dimension(304, 348));
        setPreferredSize(new java.awt.Dimension(304, 348));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelSenha2;
    private javax.swing.JLabel labelServidor2;
    private javax.swing.JLabel labelUser2;
    private javax.swing.JLabel labelUser3;
    private javax.swing.JTextField tfieldSenha1;
    private javax.swing.JTextField tfieldServer3;
    private javax.swing.JTextField tfieldUser2;
    private javax.swing.JTextField tfieldUser3;
    // End of variables declaration//GEN-END:variables

}
